A relatively simple example of an abosrbing Markov chain is the Drunkard's walk. The drunkard is always at one of $n$ intersections between his house and the pub. He wants to go home, but could also end up in the pub. If he goes home or to the pub then he will stay there. But at each of the $n$ intersections inbetween his house and the pub, there is the probabilty $p=\frac{1}{2}$ that his alcohol consumption leads to confusion and that he ends up back at the previous intersection.

Let's keep things relatively simple and take the case $n=3$. We know that there are two absorbing states for te drunkard being home or in the pub; these obviously have probability $p=1$. For simplicity, we make the two absorbing states the 4th and 5th states respectively.

In [4]:
import numpy as np
P = np.array([
            [0, 0.5, 0, 0.5, 0],
            [0.5, 0, 0.5, 0, 0],
            [0, 0.5, 0, 0, 0.5],
            [0, 0, 0, 1, 0],
            [0, 0, 0, 0, 1] ] )

In [5]:
P

array([[0. , 0.5, 0. , 0.5, 0. ],
       [0.5, 0. , 0.5, 0. , 0. ],
       [0. , 0.5, 0. , 0. , 0.5],
       [0. , 0. , 0. , 1. , 0. ],
       [0. , 0. , 0. , 0. , 1. ]])

In [7]:
from absorbing_markov_chain.absorbing_markov_chain import AbsorbingMarkovChain

In [8]:
drunkards_walk = AbsorbingMarkovChain(2,P)

In [14]:
Q = drunkards_walk.transient_matrix()

In [15]:
Q

array([[0. , 0.5, 0. ],
       [0.5, 0. , 0.5],
       [0. , 0.5, 0. ]])

In [10]:
F = drunkards_walk.fundamental_matrix()

In [11]:
F

array([[1.5, 1. , 0.5],
       [1. , 2. , 1. ],
       [0.5, 1. , 1.5]])

In [16]:
drunkards_walk.absorb_times()

array([3., 4., 3.])

In [17]:
drunkards_walk.absorb_probs()

array([[0.75, 0.25],
       [0.5 , 0.5 ],
       [0.25, 0.75]])