A relatively simple example of an abosrbing Markov chain is the Drunkard's walk. The drunkard is always at one of $n$ intersections between his house and the pub. He wants to go home, but could also end up in the pub. If he goes home or to the pub then he will stay there. But at each of the $n$ intersections inbetween his house and the pub, there is the probabilty $p=\frac{1}{2}$ that his alcohol consumption leads to confusion and that he ends up back at the previous intersection.

Let's keep things relatively simple and take the case $n=3$. We know that there are two absorbing states for te drunkard being home or in the pub; these obviously have probability $p=1$. For simplicity, we make the two absorbing states the 4th and 5th states respectively.

First define the canonical matrix:

In [9]:
import numpy as np
P = np.array([
            [0, 0.5, 0, 0.5, 0],
            [0.5, 0, 0.5, 0, 0],
            [0, 0.5, 0, 0, 0.5],
            [0, 0, 0, 1, 0],
            [0, 0, 0, 0, 1] ] )
print(P)

[[0.  0.5 0.  0.5 0. ]
 [0.5 0.  0.5 0.  0. ]
 [0.  0.5 0.  0.  0.5]
 [0.  0.  0.  1.  0. ]
 [0.  0.  0.  0.  1. ]]


Next we import the class:

In [1]:
from absorbing_markov_chain.absorbing_markov_chain import AbsorbingMarkovChain

Then define the object with 2 absorbing states for the canonical matrix $P$:

In [4]:
drunkards_walk = AbsorbingMarkovChain(2,P)

The matrix $Q$ representing transient states:

In [5]:
Q = drunkards_walk.transient_matrix()

In [6]:
print(Q)

[[0.  0.5 0. ]
 [0.5 0.  0.5]
 [0.  0.5 0. ]]


The fundemental matrix $F$:

In [7]:
F = drunkards_walk.fundamental_matrix()

In [8]:
print(F)

[[1.5 1.  0.5]
 [1.  2.  1. ]
 [0.5 1.  1.5]]


Calculate the expected number of steps before being absorbed in any absorbing state when starting in a transient states $i = 1,2,3$:

In [10]:
absorb_times = drunkards_walk.absorb_times()

In [11]:
print(absorb_times)

[3. 4. 3.]


Calculate the probability of being absorbed in either of the absorbing states when starting in a transient state $i=1,2,3$:

In [12]:
absorb_probs = drunkards_walk.absorb_probs()

In [14]:
print(absorb_probs)

[[0.75 0.25]
 [0.5  0.5 ]
 [0.25 0.75]]
