In [8]:
import numpy as np

In [9]:
from absorbing_markov_chain.absorbing_markov_chain import AbsorbingMarkovChain

The game of Snakes and Ladders is memorylessness/has the Markov property: at a given point in the game, the player's progression from the current square is independent of how they arrived at that square.

In [ ]:
https://scipython.com/book/chapter-6-numpy/additional-problems/analysing-snakes-and-ladders-as-a-markov-chain/

- The board has squares 0 to 100. 
- Player rolls a single die upon each turn
- First player to reach square 100 wins the game
- So square 100 is an absorbing state

Every time a player rolls the die, there are 6 possible options each with probability $\frac{1}{6}$. Imagine a player starting from square 0. Then the probability vector for this square is:

$$ \left[0, \frac{1}{6}, \frac{1}{6}, \frac{1}{6}, \frac{1}{6}, \frac{1}{6}, \frac{1}{6}, 0, \ldots, 0 \right] $$

The probability vector for a player at square 1 is 

$$ \left[0, 0, \frac{1}{6}, \frac{1}{6}, \frac{1}{6}, \frac{1}{6}, \frac{1}{6}, \frac{1}{6}, 0, \ldots, 0 \right] $$

and so on.

But when we get to squares 96, 97, 98, and 99, the probability vector is different since we assume that we do not need to throw the die in such a way as to get a value to take us to square 100 exactly. So the probability vector is

$$ \text{Square 94:} \quad \left[0, \ldots. 0, \frac{1}{6}, \frac{1}{6}, \frac{1}{6}, \frac{1}{6}, \frac{1}{6}, \frac{1}{6} \right]  $$

What does the matrix $P$ look like?

$$P=\left\lbrack \matrix{
     p_{1,1} & p_{1,2} & \cdots & p_{1,N} \cr
     p_{2,1} & p_{2,2} & \cdots & p_{2,N} \cr
     \vdots & \vdots & \ddots & \vdots \cr
     p_{N,1} & p_{N,2} & \cdots & p_{N,N}
 } \right\rbrack$$ 


Let's make the matrix using numpy

In [10]:
P = np.zeros((101, 101))

In [11]:
P

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [12]:
for i in range(1,101):
    P[i-1,i:i+6] = 1/6

In [13]:
P

array([[0.        , 0.16666667, 0.16666667, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.16666667, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.16666667,
        0.16666667],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.16666667],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [19]:
# House rules: you don't need to land on 100, just reach it.
P[95:100,100] += np.linspace(1/6, 5/6, 5)

In [20]:
P

array([[0.        , 0.16666667, 0.16666667, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.16666667, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.16666667,
        0.83333333],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [32]:
P[95,100]

0.3333333333333333

In [35]:
P[96,100]

0.5

In [36]:
P[100,100]

0.0